site_name: cwz-test
site_description: Connected Work Zones Implementation Guide and Standard
repo_url: https://github.com/MInsignares/cwz-test
nav:
  - Front Matter:
      - Title Page: index.md
      - Notices: notices.md
      - Acknowledgements: acknowledgements.md
      - Foreword: foreword.md
      - Executive Summary: executive-summary.md
  - 1 General Information: general-information.md
  - 2 Concept of Operations: concept-of-operations.md
  - 3 System Requirements: system-requirements.md
  - 4 System Interface Design Details Dialogs: dialogs.md
  - 5 System Interface Design Details Data Concepts: data-concepts.md
  - 6 Guidance Needs: guidance-needs.md
  - A Protocol Requirements List: protocol-requirements-list.md
  - B Requirements Traceability Matrix: requirements-traceability-matrix.md
  - C Guidance for Deployments Involving Connected Vehicle Environment Work Zone-related Standards: annex-c-guidance-connected-vehicle-environment.md
  - D Recommendations to SDOs: annex-d-recommendations-to-sdos.md
  - E User Requests: annex-e-user-requests.md
  - F Listing of Differences between the CWZ Standard and the WZDX v4.2 Specification JSON Schemas: annex-f-differences-wzdx4-2-cwz1-0.md

site_url: https://MInsignares.github.io/cwz-test/
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://github.com/ite-org/cwz">Connected Work Zones Implementation Guide and Standard</a> by <span property="cc:attributionName">AASHTO-ITE-NEMA</span> is licensed under <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""></a></p>
theme:
  name: material
  features:
    - content.code.copy
    - content.status
    - content.tooltips
    - icons
    - navigation.path
    - navigation.top
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
    admonition:
      question: fontawesome/solid/comments
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
  - stylesheets/pdf.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
plugins:
  - search
  - git-revision-date-localized:
      type: date
  - to-pdf:
      author: "AASHTO / ITE / NEMA"
      copyright: "CC-BY-4.0 (https://creativecommons.org/licenses/by/4.0/)"
      cover_logo: images/aashto-ite-nema.png
      cover_subtitle: "https://MInsignares.github.io/cwz-test/latest/"
      enabled_if_env: EXPORT_PDF
      output_path: pdf/document.pdf
      ordered_chapter_level: 0
      verbose: false
  - mermaid2:
      arguments:
        theme: |
            ^(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'
        securityLevel: loose
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - meta
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - resources/glossary.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
extra:
  search:
    highlight: true
  hide:
    - title
  version:
    provider: mike
    alias: true
    default: latest
